### ISSUE TITLE
Split excel sheets to new workbooks fails

### ISSUE THREAD

**Issue by jkkbuddika** [xlwings/xlwings#1917]
#### Versions of xlwings and Python: 0.27.7 and Python 3.9

I am trying to create new workbooks from worksheets of a workbook. Eventually I want to integrate this step in a Lambda function that runs on AWS. Testing the minimal code below on WSL2 and AWS Lambda, I ran into the same error shown below. This function worked with no errors on MacOS Monterey (v12.2.1).

```python
ERROR:root:'NoneType' object has no attribute 'apps'
Traceback (most recent call last):
  File "/mnt/c/Users/kbuddika/Documents/Alamar_Repos/Benchling-Automation/test.py", line 33, in <module>
    sheet_names = split_excel_file(excel_file="sigTune_data_767dcc9fbaa91d83.xlsx")
  File "/mnt/c/Users/kbuddika/Documents/Alamar_Repos/Benchling-Automation/test.py", line 15, in split_excel_file
    with xw.App(visible=False) as app:
  File "/home/kbuddika/miniconda3/lib/python3.9/site-packages/xlwings/main.py", line 279, in __init__
    self.impl = engines.active.apps.add(
AttributeError: 'NoneType' object has no attribute 'apps'
```

Here is the code I am trying.

```python
import xlwings as xw
import logging

def split_excel_file(excel_file: str) -> list:
    try:
        sheet_names = list()
        with xw.App(visible=False) as app:
            wb = app.books.open(excel_file)
            
            for sheet in wb.sheets:
                sheet_names.append(f"{sheet.name}.xlsx")
                wb_new = app.books.add()
                sheet.copy(after=wb_new.sheets[0])
                wb_new.sheets[0].delete()
                wb_new.save(f"{sheet.name}.xlsx")
                wb_new.close()
        
        return sheet_names
    
    except Exception as error:
        logging.error(error)
        raise
    
if __name__ == "__main__":
    sheet_names = split_excel_file(excel_file="myexcel_file.xlsx")
    print(sheet_names)
```

Can someone please let me know a potential solution to get this integrated on AWS Lambda?

**Comment by fzumstein** [comment]
At the moment, Linux support is restricted to the functionality of the remote interpreter, see: https://docs.xlwings.org/en/stable/remote_interpreter.html#remote-interpreter

For your use case, you'd either have to use a reader/writer library like OpenPyXL or maybe work with the Microsoft Graph API if your files are stored on SharePoint/OneDrive.
