### ISSUE TITLE
Python 3.12.0 support. Removal of pkgutil.ImpImporter

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2342]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Sanoma
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.12.0

#### Describe your issue (incl. Traceback!)
Following the developer guide to install xlwings 3.12.0 localy I did 

```sh
pip install -e ".[all]"
```
It results in `AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`

I saw in the [docs](https://docs.python.org/3.11/library/pkgutil.html#pkgutil.ImpImporter) that `ImpImporter` is deprecated since 3.3 and is to be replaced. 

However no xlwings code is touched so perhaps it is something python related?

Traceback message
```sh
Traceback (most recent call last):
  File "/Users/hayer/.virtualenvs/xlwings/bin/pip", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    self.handle_pip_version_check(options)
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 179, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/Users/hayer/.virtualenvs/xlwings/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by Jeroendevr** [comment]
As shown here in the [Cpython](https://github.com/python/cpython/issues/108541#issuecomment-1694701604) GitHub it could be related to `Setuptools` When upgrading to 68.2.2 I have another error message but quite similar. 
I think it is unrelated to xlwings but to VirtualFish I am using.

**Comment by Jeroendevr** [comment]
Yep It had to do with my `virtualenv` versioning and probably also `setuptools`. Now it works
