### ISSUE TITLE
Cannot call Python script from macro

### ISSUE THREAD

**Issue by miguelf88** [xlwings/xlwings#1761]
I am working with xlwings v0.25.0 and have the matching version for the Excel add-in. I am also using Office 365 and Python 3.7.4.

I am trying to run a Python script, testing_xlwings.py from a vba macro in Excel.
```
import xlwings as xw

def main():
    sheet = xw.Book.caller().sheets[0]
    sheet.range('B10').value = 'IT WORKED!!!'
```
I have assigned the macro to the button and when I click to run, I receive the following error `Compile error: Sub or Function not defined.` My sub for the macro looks like this:
```
Sub Run_xlwings()
    RunPython "import testing_xlwings.py; testing_xlwings.main()"
End Sub
```
If I change `sheet = xw.Book.caller().sheets[0]` to `sheet = xw.Book('testing_workbook.xlsm').sheets[0]` the script executes and the text is placed in the Excel file.

I have also downloaded the Monte Carlo example from the xlwings examples page. When I open the file and try to run the .py script using the macro, I receive this error: AttributeError: module 'xlwings.utlis' has no attribute 'prepare_sys_path'

**Comment by ericbmoreira** [comment]
Try this, note the parentheses.;
'''Sub Run_xlwings()
    RunPython ("import testing_xlwings.py; testing_xlwings.main()")
End Sub
'''

**Comment by fzumstein** [comment]
This sounds like a regression with 0.25.0 as this included a major refactor -- however, I wasn't able to replicate this on my end. For a quick fix, you may want to try to downgrade to 0.24.9 via `pip install xlwings==0.24.9` followed by `xlwings addin install` or you may unlock the xlwings add-in in the VBA editor (pw is `xlwings`) and see about which Sub or Function it complains?

**Comment by miguelf88** [comment]
I was able to get it to run by going into by going into the VBA editor and selecting Tools -> References and ticking the box for xlwings.

**Comment by fzumstein** [comment]
Thanks for posting your solution. If you start with a `quickstart` project, the Reference should already be there.

**Comment by Hochiss** [comment]
@fzumstein  I have the same problem as OP, i.e. the `RunPython` command is not recognized from Excel/VBA sub although I have no problem to use the button "Run main" from xlwing tab.

would you explain the difference between using `xlwing quickstart myproject` vs. write a sub afterwards adding to present myproject.xlsm? how to enable this afterwards? 

In fact, even `RunPython ""` brings an error.

**Comment by fzumstein** [comment]
You need to set a Reference to the xlwings library, see: https://docs.xlwings.org/en/latest/addin.html#installation
