### ISSUE TITLE
The `caller` argument is not populated if it has a type hint of `xw.Range`

### ISSUE THREAD

**Issue by sb02dev** [xlwings/xlwings#2536]
#### 0.33.2, Office 365, Python 3.9

The `caller` argument is not populated if it has a type hint of `xw.Range`. Below the traceback for get_caller_address, get_caller_address2 returns the expected $K$2 if called from cell K2. I would expect this either to work with hints, 
or to mention in the docs that I should not use type hints.

```python
AttributeError: 'NoneType' object has no attribute 'address'
    return caller.address
  File "C:\Users\vatusagb\Desktop\_MUNKAK\dev\xl\pyUNIQARisk\utils\xl_utils.py", line 364, in get_caller_address
    ret = func(*args)
  File "C:\Users\vatusagb\Anaconda3\lib\site-packages\xlwings\udfs.py", line 536, in call_udf
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\vatusagb\Anaconda3\lib\site-packages\xlwings\com_server.py", line 235, in CallUDF
    return func(*args)
  File "C:\Users\vatusagb\Anaconda3\lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\vatusagb\Anaconda3\lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\vatusagb\Anaconda3\lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

@xw.func
def get_caller_address(caller: xw.Range):
  return caller.address

@xw.func
def get_caller_address2(caller):
  return caller.address

```

**Comment by fzumstein** [comment]
Oh I see, yes, this must have been introduced with https://github.com/xlwings/xlwings/pull/2494.
We'll need to introduce specific type hints for the caller, something like `xw.CallerRange`.
